'use client';
import { ArrowDownRight, ArrowUpRight, Menu, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

function Mark({ className = '' }: { className?: string }) {
  return <svg className={className} viewBox="0 0 120 150" aria-hidden="true"><path d="M12 76C12 43 42 40 60 76C78 40 108 43 108 76C108 105 77 119 60 137C43 119 12 105 12 76Z" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/><path d="M60 126V41M38 62L60 38L82 62" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/><path d="M46 22C49 12 56 8 60 8C64 8 71 12 74 22L60 35L46 22Z" fill="#FFFF00"/></svg>;
}
function BrandMark({className='' }:{className?:string}){return <img className={className} src="/inspira-isotipo-transparent.png" alt=""/>}
function Logo({light=false,full=false,className=''}:{light?:boolean;full?:boolean;className?:string}){return <a href="#inicio" className={`logo ${className}`} aria-label="Inspira Más - inicio"><img src={full?(light?'/inspira-logo-light.png':'/inspira-logo-dark.png'):'/inspira-wordmark-color.png'} alt={full?'Inspira+ · María Paula Araujo':'Inspira+'}/></a>}

const achievements=[
  ['Presidenta del gobierno estudiantil','Escuela de liderazgo más grande de Latinoamérica — Competencias Líderes'],
  ['Becaria Fundación Leonidas Ortega Moreira','Beca del 50% para estudios desde básica superior hasta bachillerato'],
  ['Embajadora de Guayaquil — Inspiring Girls','Fundación Inspiring Girls Ecuador, promoviendo referentes femeninos para niñas y jóvenes.'],
  ['Outstanding Youth Program — Inglés B2 (100%)','Beca completa para estudiar inglés, otorgada por la Embajada de EE.UU. junto al Centro Ecuatoriano Norteamericano.'],
  ['Youth Ambassadors — Embajada de EE.UU.','Programa de liderazgo juvenil de la Embajada de los Estados Unidos en Ecuador.'],
  ['Conductora del programa After Class','Centro de Estudios Espíritu Santo — conducción del programa educativo After Class.'],
  ['Abanderada del Pabellón Nacional','Promedio de 9.95 — máximo honor académico de su promoción del Centro de Estudios Espíritu Santo.'],
  ['Mejor Bachiller Bilingüe de la Promoción','Centro de Estudios Espíritu Santo — reconocimiento a la excelencia académica y el bilingüismo.'],
  ['Women Economic Forum Ecuador 2023','Ponente en uno de los foros económicos femeninos más importantes de la región.'],
  ['Youth 360','Directora y fundadora del programa de liderazgo lanzado en alianza con la Dirección de la Mujer del Municipio de Guayaquil.'],
  ['Programa Artemis','Programa para fomentar el interés en las áreas STEAM, brindado por el Centro Ecuatoriano Norteamericano y la Embajada de los Estados Unidos.'],
  ['Escuela Réplica — Competencias Líderes','Charlas en escuelas réplicas junto a la Fundación Leonidas Ortega Moreira, dirigidas a jóvenes de 13 a 18 años, enfocadas en liderazgo y desarrollo personal.'],
  ['Host del evento Super Niñas','Evento de Guayaquil que reconoce y visibiliza a niñas líderes en distintas áreas para promover el empoderamiento femenino.'],
  ['Directora de Inspira+','Programa que impulsa a jóvenes a desarrollar liderazgo, propósito y habilidades para generar impacto en su comunidad.'],
  ['Becaria Jóvenes Creativos','Programa que forma a jóvenes en tecnología, emprendimiento y habilidades para su futuro profesional.'],
  ['Beca Lester B. Pearson — Universidad de Toronto','Una de las becas internacionales más prestigiosas del mundo para estudiantes de excelencia.']
];

function CountUp({end,prefix=''}:{end:number;prefix?:string}){
  const ref=useRef<HTMLElement>(null); const [value,setValue]=useState(0);
  useEffect(()=>{const node=ref.current;if(!node)return;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();if(reduce){setValue(end);return}const start=performance.now();const duration=720;const tick=(now:number)=>{const progress=Math.min((now-start)/duration,1);setValue(Math.round(end*(1-Math.pow(1-progress,3))));if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)},{threshold:.35});observer.observe(node);return()=>observer.disconnect()},[end]);
  return <strong ref={ref}>{prefix}{value}</strong>
}

function AdvisoryDetails(){return <div className="advisory-details"><p className="mini-label">ASESORÍA DE PERFIL</p><h3>Construye un perfil universitario sólido y competitivo.</h3><section><p>Diseñada para estudiantes que buscan fortalecer estratégicamente su perfil con miras a procesos de admisión, especialmente en universidades competitivas y programas de becas. Se enfoca exclusivamente en el análisis, diagnóstico y direccionamiento del perfil, alineado a la carrera de interés y a sus objetivos académicos futuros.</p></section><section><h4>Metodología de trabajo</h4><ol><li><strong>Fase de diagnóstico.</strong> El estudiante completa previamente un formulario estructurado sobre su trayectoria académica, actividades extracurriculares, intereses, logros y proyección profesional.</li><li><strong>Fase de análisis.</strong> Se identifican fortalezas actuales, áreas de mejora, nivel de competitividad y coherencia entre intereses, actividades y carrera deseada.</li><li><strong>Sesión de asesoría vía Zoom.</strong> Se presenta el análisis completo y recomendaciones de actividades extracurriculares, programas, voluntariados, experiencias y lineamientos para construir un perfil sólido.</li></ol></section><div className="advisory-columns"><section><h4>Alcance</h4><ul><li>Construcción y mejora del perfil.</li><li>Recomendaciones alineadas a la carrera de interés.</li><li>Sin acompañamiento continuo ni seguimiento posterior.</li></ul></section><section className="price-card"><h4>Inversión</h4><strong>$45 USD</strong><p>Se acepta el pago mediante transferencia bancaria.</p></section></div><div className="service-actions"><a className="button button--light pulse-button" href="https://ig.me/m/inspira.ecu.ec" target="_blank" rel="noreferrer">Contáctanos <ArrowUpRight/></a></div></div>}

export default function Home() {
  const [open,setOpen]=useState(false); const close=()=>setOpen(false); const galleryRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const nodes=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);
  return <main id="inicio">
    <nav className="nav" aria-label="Navegación principal"><Logo/><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Abrir menú">{open?<X/>:<Menu/>}</button><div className={`nav-links ${open?'open':''}`}><a onClick={close} href="#que-es-inspira">Inspira+</a><a onClick={close} href="#servicios">Servicios</a><a onClick={close} href="#maria-paula">Nuestra directora</a><a onClick={close} href="#impacto">Impacto</a><a onClick={close} href="#voluntariado">Voluntariado</a></div></nav>
    <section className="hero">
      <div className="hero-copy"><h1>Tu potencial<br/>puede abrir<br/><em>puertas</em> al mundo.</h1><p className="hero-lead">Descubre oportunidades. Construye tu perfil.<br/>Prepárate para alcanzarlas.</p><div className="hero-actions"><a className="button" href="#servicios">Quiero potenciar mi perfil <ArrowUpRight/></a><a className="text-link" href="#que-es">Conoce Inspira Más <ArrowDownRight/></a></div></div>
      <div className="hero-art" aria-label="Comunidad Inspira Más"><img className="hero-photo" src="/foto-portada.jpg" alt="Jóvenes de la comunidad Inspira Más"/><span className="orbit orbit--one">BECAS</span><span className="orbit orbit--two">LIDERAZGO</span><span className="orbit orbit--three">OPORTUNIDADES</span></div>
    </section>
    <section id="que-es" className="intro"><div className="intro-grid"><h2>Tienes potencial.<br/>Pero… <span>¿sabes cómo convertirlo en oportunidades?</span></h2></div></section>

    <section id="que-es-inspira" className="about section-pad"><div className="section-kicker">QUÉ ES INSPIRA+</div><div className="about-head reveal"><h2>Más que oportunidades.<br/><span>Un camino para alcanzarlas.</span></h2><div className="about-story"><p>Inspira+ nace con una misión: ayudar a jóvenes a descubrir oportunidades y prepararse para alcanzarlas.</p><p>Sabemos que existen becas, programas, certificaciones y experiencias increíbles, pero muchas veces el problema no es la falta de talento, sino no saber por dónde empezar.</p><p>Por eso, a través de contenido, asesorías y mentorías, ayudamos a cada joven a reconocer su potencial, fortalecer su perfil y construir una trayectoria con propósito.</p><p>Porque no se trata solo de encontrar oportunidades, sino de estar preparado para cuando lleguen.</p><strong>Inspira+ — Creando perfiles que abren puertas al mundo.</strong></div></div><div className="verbs"><article><strong>Descubre</strong><p>Becas, programas, certificaciones y convocatorias.</p></article><article><strong>Construye</strong><p>Fortalece tu perfil con experiencias y estrategia.</p></article><article><strong>Conecta</strong><p>Encuentra personas, recursos y comunidades.</p></article><article><strong>Crece</strong><p>Convierte tus metas en próximos pasos.</p></article></div></section>

    <section className="method section-pad"><div className="method-top reveal"><div><div className="section-kicker">NUESTRO MÉTODO</div><h2>No creemos en perfiles perfectos.</h2></div><p>Creemos en <strong>perfiles estratégicos:</strong> historias auténticas con una dirección clara.</p></div><div className="steps"><article><i>01</i><h3>Conócete</h3><p>Identificamos quién eres, qué has construido y hacia dónde quieres ir.</p></article><article><i>02</i><h3>Analiza</h3><p>Detectamos fortalezas y áreas de desarrollo en tu perfil.</p></article><article><i>03</i><h3>Construye</h3><p>Creamos experiencias y acciones alineadas con tus objetivos.</p></article><article><i>04</i><h3>Conecta</h3><p>Identificamos oportunidades que realmente se alinean contigo.</p></article><article><i>05</i><h3>Aplica</h3><p>Preparamos tu perfil y tu historia para dar el siguiente paso.</p></article></div></section>

    <section id="servicios" className="services"><div className="services-title section-pad reveal"><div className="section-kicker">SERVICIOS</div><h2>Dos formas de acompañarte.<br/><span>Un mismo objetivo.</span></h2></div><article className="service service--coral service--advisory"><AdvisoryDetails/></article><article className="service service--purple"><div className="service-copy"><p className="mini-label">MENTORÍA PERSONALIZADA</p><h3>Tu postulación, con estrategia y acompañamiento en cada paso.</h3><p>Te acompañamos durante todo el proceso para que construyas una postulación sólida, auténtica y competitiva para becas y oportunidades internacionales.</p><h4>¿Qué incluye?</h4><ul className="mentoring-list"><li><strong>Estrategia personalizada</strong><span>Definimos cómo potenciar tu perfil y presentar tu historia.</span></li><li><strong>Revisión de ensayos y documentos</strong><span>Feedback y recomendaciones sin perder tu propia voz.</span></li><li><strong>10 sesiones 1:1</strong><span>Sesiones personalizadas según tu proceso y avances.</span></li><li><strong>Seguimiento continuo</strong><span>Acompañamiento y resolución de dudas vía WhatsApp.</span></li><li><strong>Preparación para entrevistas</strong><span>Simulaciones, práctica y retroalimentación personalizada.</span></li><li><strong>Organización de tu aplicación</strong><span>Fechas, requisitos, documentos y avances bajo control.</span></li></ul><div className="mentor-price">Inversión: <strong>$685 USD</strong></div><div className="service-actions"><a className="button button--turquoise pulse-button" href="https://ig.me/m/inspira.ecu.ec" target="_blank" rel="noreferrer">Contáctanos <ArrowUpRight/></a></div></div></article></section>

    <section id="maria-paula" className="founder section-pad"><div className="founder-image"><img className="founder-photo" src="/maria-paula.jpg" alt="María Paula Araujo Munizaga"/><span className="speaker-tag">SPEAKER · MENTORA</span></div><div className="founder-copy reveal"><div className="section-kicker">NUESTRA DIRECTORA</div><h2>María Paula<br/><span>Araujo</span></h2><p className="founder-role">Fundadora & Directora · Speaker · Líder juvenil · Mentora</p><blockquote>“Lo que Dios preparó para ti, no le sirve a nadie más.”</blockquote><div className="founder-bio"><p>María Paula Araujo Munizaga es líder juvenil, speaker motivacional y una apasionada por abrir oportunidades para otros jóvenes.</p><p>Desde los 13 años comenzó a realizar voluntariados, participar en programas y ganar becas. Cada una de esas experiencias fue construyendo su perfil y definiendo su camino.</p><p>Actualmente empodera y asesora a jóvenes para que crean en su potencial, exploren carreras STEM y accedan a oportunidades globales, como becas internacionales.</p><p>Su propósito es claro: democratizar el acceso a la educación y formar una nueva generación de líderes que no tengan miedo de soñar en grande.</p></div></div></section>

    <section id="impacto" className="impact section-pad"><div className="impact-head"><div className="section-kicker">IMPACTO</div><h2 className="reveal">Los <span>números</span> cuentan parte de la historia.</h2><p>Cada cifra forma parte de los caminos que he impactado a través de mis charlas, asesorías y mis proyectos. La verdadera medida está en las vidas que he transformado.</p></div><div className="metrics"><article><CountUp end={1500} prefix="+"/><span>Jóvenes alcanzados</span><small>Con mis charlas y asesorías</small></article><article><CountUp end={35} prefix="+"/><span>Países impactados</span><small>Con mis conferencias y sesiones personalizadas</small></article><article><CountUp end={10} prefix="+"/><span>Becas obtenidas</span><small>En más de 3 países</small></article><article><CountUp end={2}/><span>Iniciativas lideradas</span><small>Directora de Inspira+ y Youth 360</small></article></div></section>

    <section className="achievements section-pad"><div className="achievement-bar"><div className="section-kicker">LOGROS</div><button type="button" onClick={()=>galleryRef.current?.scrollBy({left:520,behavior:'smooth'})} aria-label="Avanzar en la galería">Desliza para avanzar <ArrowUpRight/></button></div><div ref={galleryRef} className="achievement-track">{achievements.map(([title,description],index)=><article key={index}><div className="achievement-photo"><img src={`/gallery/${index+1}.jpg`} alt={`${title} — imagen ${index+1}`}/></div><i>{String(index+1).padStart(2,'0')}</i><div className="achievement-copy"><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>

    <section className="stories section-pad"><div className="section-kicker">NUESTROS TESTIMONIOS</div><h2>Ellos también decidieron dar el siguiente paso.</h2><div className="testimonials"><article><span>01</span><blockquote>“Aquí irá un testimonio real sobre el cambio vivido después de la asesoría o mentoría.”</blockquote><p>Nombre · edad · país / institución</p></article><article><span>02</span><blockquote>“Aquí irá un testimonio real con un resultado concreto y verificable.”</blockquote><p>Nombre · edad · país / institución</p></article><article><span>03</span><blockquote>“Aquí irá la voz de otro joven que construyó una ruta más clara.”</blockquote><p>Nombre · edad · país / institución</p></article></div></section>

    <section id="voluntariado" className="community"><article className="volunteer"><div className="section-kicker">VOLUNTARIADO</div><h2>Realiza un voluntariado con nosotros.</h2><p>Participa desde nuestra <strong>área de Marketing</strong> o desde el área de <strong>Investigación y Oportunidades</strong>. Creamos espacios para jóvenes que quieren comunicar, investigar y acercar nuevas posibilidades a su comunidad.</p><a className="button volunteer-button" href="https://forms.gle/1cLs17nwRvLSNfpW7" target="_blank" rel="noreferrer">Quiero ser parte <ArrowUpRight/></a></article></section>

    <section id="contacto" className="final-cta section-pad"><BrandMark className="final-mark"/><Logo light full className="final-logo"/><p className="section-kicker">TU SIGUIENTE PASO</p><h2>¿Qué puerta<br/>quieres <span>abrir?</span></h2><p>No importa si todavía no sabes exactamente cómo llegar. El primer paso es descubrir de qué eres capaz y empezar a construirlo.</p><div className="final-actions"><a className="button button--yellow" href="https://www.instagram.com/inspira.ecu.ec?igsi=YndkY3U3ejViZXl4&utm_source=qr" target="_blank" rel="noreferrer">Nuestro Instagram <ArrowUpRight/></a></div></section>
    <footer><Logo/><p>Oportunidades · Perfil · Liderazgo · Futuro</p><a href="#inicio">Volver arriba ↑</a></footer>
  </main>;
}
